= CalConnect Standard: (TITLE)

This work item belongs to CalConnect (TCs).

image:https://github.com/CalConnect/cc-vcard-schedulable/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-vcard-schedulable/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-vcard-schedulable/[CalConnect: Schedulable Objectclass for vCard]

== General

This document defines a new objectclass value "schedulable" for vCard that
enables entities to be marked as schedulable.

It includes:

* Required and recommended properties for schedulable entities
* New properties specific to scheduling functionality
* New parameter values for existing properties
* Recommendations for calendaring systems

== Content

This document specifies the vCard Schedulable Objectclass.

The document is published as the following:

* CalConnect CC 58011
* IETF draft-vcard-schedulable


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-vcard-schedulable/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== IETF: Checking against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
submissions.

[source,sh]
----
idnits {filename}.nits
----


== License

Copyright its respective authors and CalConnect.
