[[examples]]
== Examples

=== Schedulable

A schedulable entity can be scheduled for meetings (as a person) or
for use (as a resource). For a scheduling system to be able to
usefully manage the schedule it needs specific information.

At the very least there MUST be some form of calendar user address.
It's useful to know whether requests can be auto accepted if the slot
is available.

[source]
----
BEGIN:VCARD
VERSION:4.0
UID:urn:uuid:4fbe8971-0bc3-424c-9c26-36c3e1eff6b1
FN:J. Doe
N:Doe;J.;;;
EMAIL:jdoe@example.edu
TEL;VALUE=uri:tel:+1-555-555-5555
OBJECTCLASS:schedulable
CALADRURI:jdoe@example.edu
AUTOSCHEDULE:ACCEPT-IF-FREE
END:VCARD
----

== Recommendations for Calendaring Systems

While this document does not mandate how each of the defined
property values must be used by calendaring systems, here are
some recommendations:

. BOOKINGWINDOWSTART (<<bwin_start>>),
BOOKINGWINDOWEND (<<bwin_end>>)
and MULTIBOOK (<<multibook>>)
information should be used in freebusy calculations.
A query for a time slot that falls outside the booking window or one
that already has the maximum allowed number of simultaneous
bookings, MUST be returned as BUSY_UNAVAILABLE.

. Calendaring systems that support the AUTOSCHEDULE
(<<auto>>)
property, SHOULD automatically mark the attendee PARTSTAT
for a resource as ACCEPTED, if its auto schedule value is AUTO
and the scheduling is successful. If scheduling administrator
approval is required, the PARTSTAT could be automatically
marked as TENTATIVE. Rooms SHOULD have this property defined.

. Information from other properties, for example the capacity if a
resource can be used by calendaring systems to warn end users if the
number of attendees exceed the capacity value. Rooms SHOULD
have CAPACITY defined.

Individual calendar servers may regard the values of these
properties set in a directory server or a different database as
advisory and could further limit what it allows.
