== Recommendations for Calendaring Systems

While this document does not mandate how each of the defined property
values must be used by calendaring systems, here are some
recommendations:

. BOOKINGWINDOWSTART (<<bwin_start>>),
BOOKINGWINDOWEND (<<bwin_end>>)
and MULTIBOOK (<<multibook>>)
information should be used in
freebusy calculations.  A query for a time slot that falls
outside the booking window or one that already has the maximum
allowed number of simultaneous bookings, MUST be returned as
BUSY_UNAVAILABLE.

. Calendaring systems that support the AUTOSCHEDULE (<<auto>>)
property, SHOULD automatically mark the attendee PARTSTAT for a
resource as ACCEPTED, if its auto schedule value is AUTO and the
scheduling is successful.  If scheduling administrator approval
is required, the PARTSTAT could be automatically marked as
TENTATIVE.  Rooms SHOULD have this property defined.


. Information from other properties, for example the capacity if a
  resource can be used by calendaring systems to warn end users if
  the number of attendees exceed the capacity value.  Rooms SHOULD
  have CAPACITY defined.

Individual calendar servers may regard the values of these properties
set in a directory server or a different database as advisory and
could further limit what it allows.